export {
  mouseAnswersSchema,
  audioAnswersSchema,
  keyboardAnswersSchema,
  monitorAnswersSchema,
  validateMouseAnswers,
  validateAudioAnswers,
  validateKeyboardAnswers,
  validateMonitorAnswers,
  searchParamsToObject,
  type ValidatedMouseAnswers,
  type ValidatedAudioAnswers,
  type ValidatedKeyboardAnswers,
  type ValidatedMonitorAnswers,
} from "./quiz-schemas";
