import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import NavbarV2 from "@/components/landing-v2/NavbarV2";
import FooterV2 from "@/components/landing-v2/FooterV2";

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <NavbarV2 />

      {/* Hero Section */}
      <section className="pt-32 pb-16 md:pt-40 md:pb-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto">
            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
              Terms of <span className="text-gradient">Service</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              The rules and guidelines for using GearMatch.
            </p>
            <p className="text-sm text-muted-foreground mt-4">
              Last updated: February 2026
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto prose prose-invert prose-lg">
            <div className="space-y-12">
              {/* Agreement */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Agreement to Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  By accessing or using GearMatch, you agree to be bound by these Terms
                  of Service. If you disagree with any part of these terms, you may not
                  access the service.
                </p>
              </div>

              {/* Eligibility */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Eligibility
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  You must be at least 13 years of age to use GearMatch. By using this
                  service, you represent and warrant that you are at least 13 years old.
                  If you are under 18, you represent that you have your parent or
                  guardian's permission to use the service. We do not knowingly collect
                  or solicit personal information from children under 13. If we learn
                  that we have collected personal information from a child under 13, we
                  will delete that information promptly.
                </p>
              </div>

              {/* Description of Service */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Description of Service
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  GearMatch is a free recommendation platform that helps users find
                  gaming peripherals (mice, keyboards, audio equipment, and monitors)
                  based on their preferences. We provide:
                </p>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Interactive quizzes to assess your needs</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Personalized product recommendations</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Product information and specifications</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Links to third-party retailers where products can be purchased</span>
                  </li>
                </ul>
              </div>

              {/* Recommendations Disclaimer */}
              <div className="bg-card border border-border rounded-2xl p-6 md:p-8">
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Recommendations <span className="text-gradient-accent">Disclaimer</span>
                </h2>
                <div className="space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    Our recommendations are generated by algorithms based on the information
                    you provide and our product database. While we strive for accuracy:
                  </p>
                  <ul className="space-y-2">
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Recommendations are suggestions, not guarantees of satisfaction
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Product specifications may change without our knowledge
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Prices and availability are determined by third-party retailers
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Personal preference and individual experience may vary
                      </span>
                    </li>
                  </ul>
                  <p>
                    We encourage you to research products independently before making
                    purchase decisions.
                  </p>
                </div>
              </div>

              {/* Product Information Disclaimer */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Product Information Disclaimer
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch explicitly disclaims responsibility for any inaccuracies,
                  errors, or omissions in our product database. Product information,
                  including but not limited to specifications, features, dimensions,
                  weights, and compatibility details, is compiled from various sources
                  and may not always be complete, accurate, or up-to-date. Manufacturers
                  may change product specifications at any time without notice. You
                  should always verify product details directly with the manufacturer
                  or retailer before making a purchase decision. GearMatch shall not be
                  held liable for any decisions made based on information in our database.
                </p>
              </div>

              {/* Affiliate Relationships */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Affiliate Relationships
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch participates in affiliate programs with various retailers.
                  When you click links to products and make purchases, we may earn
                  commissions. This does not affect the price you pay. Our recommendations
                  are based on fit with your preferences, not affiliate relationships.
                  For more information, see our{" "}
                  <Link to="/affiliate-disclosure" className="text-primary hover:underline">
                    Affiliate Disclosure
                  </Link>
                  .
                </p>
              </div>

              {/* User Conduct */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  User Conduct
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  When using GearMatch, you agree not to:
                </p>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Use the service for any unlawful purpose
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Attempt to gain unauthorized access to our systems
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Interfere with or disrupt the service or servers
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Scrape, copy, or reproduce our content without permission
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Use automated systems to access the service in a manner that sends
                      more requests than a human could reasonably produce
                    </span>
                  </li>
                </ul>
              </div>

              {/* Termination */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Termination
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to terminate or suspend your access to GearMatch
                  immediately, without prior notice or liability, for any reason
                  whatsoever, including without limitation if you breach these Terms of
                  Service. Upon termination, your right to use the service will
                  immediately cease. All provisions of these Terms which by their nature
                  should survive termination shall survive termination, including,
                  without limitation, ownership provisions, warranty disclaimers,
                  indemnity, and limitations of liability.
                </p>
              </div>

              {/* Intellectual Property */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Intellectual Property
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  The GearMatch service, including its original content, features, and
                  functionality, is owned by GearMatch and is protected by copyright,
                  trademark, and other intellectual property laws.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  Product names, logos, and brands mentioned on GearMatch are the
                  property of their respective owners. Their use does not imply
                  endorsement by those owners.
                </p>
              </div>

              {/* Third-Party Links */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Third-Party Links
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch contains links to third-party websites (retailers, product
                  pages, etc.). We have no control over, and assume no responsibility
                  for, the content, privacy policies, or practices of any third-party
                  sites or services. Your interactions with third-party sites are
                  governed by their terms and policies.
                </p>
              </div>

              {/* Limitation of Liability */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Limitation of Liability
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch is provided "as is" without warranties of any kind, either
                  express or implied. We do not warrant that the service will be
                  uninterrupted, secure, or error-free. In no event shall GearMatch be
                  liable for any indirect, incidental, special, consequential, or
                  punitive damages arising from your use of the service.
                </p>
              </div>

              {/* Indemnification */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Indemnification
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  You agree to defend, indemnify, and hold harmless GearMatch and its
                  operators from any claims, damages, obligations, losses, or expenses
                  arising from your use of the service or violation of these terms.
                </p>
              </div>

              {/* Changes to Terms */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Changes to Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to modify or replace these terms at any time.
                  When we do, we'll update the "Last updated" date at the top of this
                  page. Your continued use of the service after any changes constitutes
                  acceptance of the new terms.
                </p>
              </div>

              {/* Governing Law */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Governing Law
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms of Service shall be governed by and construed in
                  accordance with the laws of the Commonwealth of Pennsylvania, United
                  States, without regard to its conflict of law provisions. Our failure
                  to enforce any right or provision of these Terms will not be
                  considered a waiver of those rights.
                </p>
              </div>

              {/* Dispute Resolution */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Dispute Resolution
                </h2>
                <div className="space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    Any dispute, controversy, or claim arising out of or relating to
                    these Terms of Service, or the breach, termination, or invalidity
                    thereof, shall first be attempted to be resolved through informal
                    negotiation. If the dispute cannot be resolved through informal
                    negotiation within thirty (30) days, either party may initiate
                    binding arbitration.
                  </p>
                  <p>
                    Arbitration shall be conducted by a single arbitrator in accordance
                    with the rules of the American Arbitration Association. The
                    arbitration shall take place in Pennsylvania, and the language of
                    the arbitration shall be English. The arbitrator's decision shall
                    be final and binding.
                  </p>
                  <p>
                    You agree that any arbitration or court proceeding shall be
                    conducted only on an individual basis and not in a class,
                    consolidated, or representative action. If for any reason a claim
                    proceeds in court rather than arbitration, you waive any right to a
                    jury trial.
                  </p>
                </div>
              </div>

              {/* Severability */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Severability
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If any provision of these Terms of Service is held to be invalid,
                  illegal, or unenforceable by a court or other tribunal of competent
                  jurisdiction, such provision shall be limited or eliminated to the
                  minimum extent necessary, and the remaining provisions of these Terms
                  shall remain in full force and effect.
                </p>
              </div>

              {/* Entire Agreement */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Entire Agreement
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms of Service, together with our Privacy Policy and
                  Affiliate Disclosure, constitute the entire agreement between you and
                  GearMatch regarding your use of the service and supersede all prior
                  and contemporaneous written or oral agreements, communications, and
                  other understandings relating to the subject matter hereof.
                </p>
              </div>

              {/* Contact */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Contact Us
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you have questions about these Terms of Service, please contact us
                  at{" "}
                  <a
                    href="mailto:hello@gearmatch.app"
                    className="text-primary hover:underline"
                  >
                    hello@gearmatch.app
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 md:py-24 bg-gradient-section">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto">
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              Ready to Find Your <span className="text-gradient">Perfect Gear</span>?
            </h2>
            <p className="text-muted-foreground text-lg mb-8">
              Take a quiz and get personalized recommendations in minutes.
            </p>
            <Button variant="hero" size="lg" asChild>
              <Link to="/quiz/mouse">
                Get Started
                <ArrowRight className="w-4 h-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      <FooterV2 />
    </div>
  );
};

export default TermsPage;
