import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="pt-32 pb-16 md:pt-40 md:pb-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto">
            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
              Terms of <span className="text-gradient">Service</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              The rules and guidelines for using GearMatch.
            </p>
            <p className="text-sm text-muted-foreground mt-4">
              Last updated: February 2026
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto prose prose-invert prose-lg">
            <div className="space-y-12">
              {/* Agreement */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Agreement to Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  By accessing or using GearMatch, you agree to be bound by these Terms
                  of Service. If you disagree with any part of these terms, you may not
                  access the service.
                </p>
              </div>

              {/* Description of Service */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Description of Service
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  GearMatch is a free recommendation platform that helps users find
                  gaming peripherals (mice, keyboards, audio equipment, and monitors)
                  based on their preferences. We provide:
                </p>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Interactive quizzes to assess your needs</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Personalized product recommendations</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Product information and specifications</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>Links to third-party retailers where products can be purchased</span>
                  </li>
                </ul>
              </div>

              {/* Recommendations Disclaimer */}
              <div className="bg-card border border-border rounded-2xl p-6 md:p-8">
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Recommendations <span className="text-gradient-accent">Disclaimer</span>
                </h2>
                <div className="space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    Our recommendations are generated by algorithms based on the information
                    you provide and our product database. While we strive for accuracy:
                  </p>
                  <ul className="space-y-2">
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Recommendations are suggestions, not guarantees of satisfaction
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Product specifications may change without our knowledge
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Prices and availability are determined by third-party retailers
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="text-accent mt-1">•</span>
                      <span>
                        Personal preference and individual experience may vary
                      </span>
                    </li>
                  </ul>
                  <p>
                    We encourage you to research products independently before making
                    purchase decisions.
                  </p>
                </div>
              </div>

              {/* Affiliate Relationships */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Affiliate Relationships
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch participates in affiliate programs with various retailers.
                  When you click links to products and make purchases, we may earn
                  commissions. This does not affect the price you pay. Our recommendations
                  are based on fit with your preferences, not affiliate relationships.
                  For more information, see our{" "}
                  <Link to="/affiliate-disclosure" className="text-primary hover:underline">
                    Affiliate Disclosure
                  </Link>
                  .
                </p>
              </div>

              {/* User Conduct */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  User Conduct
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  When using GearMatch, you agree not to:
                </p>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Use the service for any unlawful purpose
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Attempt to gain unauthorized access to our systems
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Interfere with or disrupt the service or servers
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Scrape, copy, or reproduce our content without permission
                    </span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      Use automated systems to access the service in a manner that sends
                      more requests than a human could reasonably produce
                    </span>
                  </li>
                </ul>
              </div>

              {/* Intellectual Property */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Intellectual Property
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  The GearMatch service, including its original content, features, and
                  functionality, is owned by GearMatch and is protected by copyright,
                  trademark, and other intellectual property laws.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  Product names, logos, and brands mentioned on GearMatch are the
                  property of their respective owners. Their use does not imply
                  endorsement by those owners.
                </p>
              </div>

              {/* Third-Party Links */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Third-Party Links
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch contains links to third-party websites (retailers, product
                  pages, etc.). We have no control over, and assume no responsibility
                  for, the content, privacy policies, or practices of any third-party
                  sites or services. Your interactions with third-party sites are
                  governed by their terms and policies.
                </p>
              </div>

              {/* Limitation of Liability */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Limitation of Liability
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  GearMatch is provided "as is" without warranties of any kind, either
                  express or implied. We do not warrant that the service will be
                  uninterrupted, secure, or error-free. In no event shall GearMatch be
                  liable for any indirect, incidental, special, consequential, or
                  punitive damages arising from your use of the service.
                </p>
              </div>

              {/* Indemnification */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Indemnification
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  You agree to defend, indemnify, and hold harmless GearMatch and its
                  operators from any claims, damages, obligations, losses, or expenses
                  arising from your use of the service or violation of these terms.
                </p>
              </div>

              {/* Changes to Terms */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Changes to Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to modify or replace these terms at any time.
                  When we do, we'll update the "Last updated" date at the top of this
                  page. Your continued use of the service after any changes constitutes
                  acceptance of the new terms.
                </p>
              </div>

              {/* Governing Law */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Governing Law
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  These terms shall be governed by and construed in accordance with
                  applicable laws, without regard to conflict of law principles.
                </p>
              </div>

              {/* Contact */}
              <div>
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-4">
                  Contact Us
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you have questions about these Terms of Service, please contact us
                  at{" "}
                  <a
                    href="mailto:hello@gearmatch.app"
                    className="text-primary hover:underline"
                  >
                    hello@gearmatch.app
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 md:py-24 bg-gradient-section">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto">
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              Ready to Find Your <span className="text-gradient">Perfect Gear</span>?
            </h2>
            <p className="text-muted-foreground text-lg mb-8">
              Take a quiz and get personalized recommendations in minutes.
            </p>
            <Button variant="hero" size="lg" asChild>
              <Link to="/quiz/mouse">
                Get Started
                <ArrowRight className="w-4 h-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsPage;
